### ISSUE TITLE
How would I add this script function?

### ISSUE THREAD

**Issue by carterbryden** [fnkr/c9-scripts#4]
Hi, thanks for making this and licensing it under MIT for everyone to use. I'm not totally sure how to add something to it though, would you mind helping me out a bit?

I'm looking to create a command that lets me open files outside the workspace (apache2.conf for example) in the c9 editor rather than something like nano or vim.

A c9 employee gave me this shell script as a workaround for now:

```
edit() {
    local FILE=$(cd "$(dirname "$1")"; pwd)/$(basename "$1")
    local name=${FILE//\//}
    
    if [ ! -e "$FILE" ]; then
        echo "creating $FILE"
        touch "$FILE" || sudo touch "$FILE" > /dev/null
    elif [ -f "$FILE" ]; then
        :
    elif [ -h "$FILE" ]; then
        FILE=$(readlink "$FILE")
    else
        echo "can't edit $FILE"
        exit -1
    fi
    local TMP_DIR=~/.c9/edit-tmp
    mkdir -p "$TMP_DIR"
    [ -z "$FILE" ] && cp "$FILE" "$TMP_DIR/$name"
    c9 open --wait "$TMP_DIR/$name" 
    if [ -e "$TMP_DIR/$name" ]; then
        cat "$TMP_DIR/$name" | sudo tee "$FILE" > /dev/null
        rm "$TMP_DIR/name"
        ls -ladh "$FILE"
    fi
}
```

How would I add this to your set of scripts and alias into an easy command like c9all filename.conf?

**Comment by fnkr** [comment]
You could fork this and add your script to the [`utils` directory](https://github.com/fnkr/c9-scripts/tree/master/utils).
